### ISSUE TITLE
Connecting via thunder bird

### ISSUE THREAD

**Issue by astutesoftware** [nodemailer/smtp-server#104]
When connecting to smtp server from thunderbird, thunderbird reports that it is "probing server"
and says "Thunderbird failed to find the settings for your email account".
On the server end this is what is happening

```
Connection from [192.168.1.227]
S: 220 Chirags-MacBook-Pro.local ESMTP Welcome to My Awesome LMTP Server
C: EHLO we-guess.mozilla.org
S: 250-Chirags-MacBook-Pro.local Nice to meet you, [192.168.1.227]
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250 SIZE 10485760
C: QUIT
S: 221 Bye
Connection closed to [192.168.1.227]
```

Question  is how to le thunderbird authenticate correctly so eventually we can push mails from thunderbird. I did add the onauth handler.

Configuration screenshot is here - https://pasteboard.co/H3LHNtS.png

**Comment by andris9** [comment]
Thunderbird probably fails on POP3. I've learned that using "autodetect" usually does not work.
