### ISSUE TITLE
`connectionTimeout: 0` does not work

### ISSUE THREAD

**Issue by artemave** [nodemailer/smtp-server#105]
Because it evaluates to `false` here:

```javascript
let timeout = this.options.closeTimeout || CLOSE_TIMEOUT;
```

**Comment by andris9** [comment]
Why would you want to use 0 as timeout?

**Comment by artemave** [comment]
We use smtp-server in tests as a simulator. We want it to shut down asap between tests so that tests don't get slow.

**Comment by andris9** [comment]
Due to how timers in JavaScript work you would not get any noticeable performance gain when using 0 instead of 1.

**Comment by artemave** [comment]
The problem is not that `1` is greater than `0`, it's that when you want to disable timeout and you'd set it to `0`, it would turn out to be `300`. That is a bug.
