### ISSUE TITLE
Emit events instead of registering callbacks at construction time

### ISSUE THREAD

**Issue by strugee** [nodemailer/smtp-server#111]
I'm very confused as to how this module is supposed to work. It seems like instances of `SMTPServer` are EventEmitters, but the events that it emits aren't documented? AFAICT you're supposed to pass callbacks at construction time but this really does not work great because sometimes you want to register listeners later (this is my use case because of the way my test suite is set up) or you want to use `emitter.once` instead of `emitter.on`. The current design is super confusing and inconsistent because there are a _couple_ events you can listen for, but AFAICT most things have to be done with the `on*` options passed to the server constructor.

Let me know if I'm missing something obvious.

**Comment by andris9** [comment]
The "event" part of SMTPServer includes informational events like 'connect' etc. The callbacks you need to register are not informational but transactional and thus can't be really treated the same way events are treated. You are supposed to call your own handlers from the callback and return the result of the operation. You can see [here](https://github.com/zone-eu/zone-mta/blob/1a966d0bacac53fc69e1581b3fd66f4a8ef17f53/lib/smtp-interface.js#L128-L254) a real-life example of setting up the callbacks
