### ISSUE TITLE
How to customize response envelope

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/smtp-server#129]
In ForwardEmail.net - I'd like to map the responses from the email server I'm forwarding to back to the original RCPT.  For example, hello@nodemailer.com gets forwarded to a@gmail.com and b@gmail.com, and test@nodemailer.com gets forwarded to c@gmail.com.  If A and B are successful, but C is not, I do not want all (3) to fail.  I still want the client to know that C is not successful, and for a particular reason.  Is there a way to customize the callback second argument in `onData(stream, session, callback)` such that we could do something like `callback(null, { accepted: [ ... ], rejected: [ ... ], rejectedErrors: [ ... ] })`?

**Comment by andris9** [comment]
Not with SMTP, this is only possible with LMTP where you get a separate DATA response for each RCPT. With SMTP all recipients fail or succeed at once. The correct way to handle this is to accept the messages, and then generate bounce emails for failed recipients.

**Comment by niftylettuce** [comment]
Brilliant

**Comment by andris9** [comment]
For generating bounces you should use a checklist:

* No bounces for messages with `Auto-Submitted` or `X-Auto-Response-Suppress` headers
* original MAIL FROM must not be blank (this indicates the original message is already a bounce)
* Messages must not have too many `Received` headers to prevent eternal loops. This also applies to normally forwarded messages. If a message has already 20-30 Received headers then something is fishy
* No bounces for messages that look like spam

You can check out an example for generating a bounce message from [zone-mta bounce handler](https://github.com/zone-eu/zone-mta/blob/7b03e954726f54ffa1fd7eff83487913cc46d2ab/plugins/core/email-bounce.js#L9-L81)

**Comment by niftylettuce** [comment]
@andris9 thanks for this - following up here, I think that your statement here is inaccurate:

> No bounces for messages with `Auto-Submitted` or `X-Auto-Response-Suppress` headers

Instead, I think we should check the following:
* X-Autoreply
* X-Autorespond
* auto-submitted with a value of "auto-replied"

Ref: <https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/>

**Comment by niftylettuce** [comment]
@andris9 Just a follow up - your Zone MTA code would result in the following bounce in Gmail:

![Screen Shot 2020-05-17 at 5 16 19 AM](https://user-images.githubusercontent.com/523141/82145188-a6957c00-980e-11ea-9698-ffaaf237c7ce.png)

I've fixed it on my side, and now it looks like this:

![Screen Shot 2020-05-17 at 7 15 56 AM](https://user-images.githubusercontent.com/523141/82145194-aac19980-980e-11ea-923d-701cfff06e14.png)

If you're curious how I fixed it, see this: <https://github.com/forwardemail/free-email-forwarding/blob/cb2a2e3b6bc47740a90b2a110d868dab723cb840/index.js#L416-L511>
