### ISSUE TITLE
How to save the email riceived?

### ISSUE THREAD

**Issue by realtebo** [nodemailer/smtp-server#133]
I see that using this code I can output stream to video
```
onData(stream, session, callback) {
    stream.pipe(process.stdout); // print message to console
    stream.on("end", callback);
  }
```

But, how can I SAVE received stream?
How can I capture all the stream into a variable, for example?

**Comment by xdevnull** [comment]
You need to parse stream You can use **SimpleParser**. 

https://github.com/nodemailer/mailparser

```
onData(stream, session, callback) {
    simpleParser(stream, (err, parsed) => {
        // store 
    });
  }
```
