### ISSUE TITLE
Receive duplicate emails from outlook.com

### ISSUE THREAD

**Issue by ducdev** [nodemailer/smtp-server#160]
Hi,

I sent emails from my personal email address ***@live.com to an email address running with smtp-server. I realized that I received duplicated emails, more than twice for each copy. I think that the sender didn't know that the emails were arrived, there should be a way to let them know about delivery status.

Hope to hear back from you.
Thanks for making this great package.

**Comment by jvlobo** [comment]
I'm also seeing this behaviour on my server. I keep receiving the same email over and over.
Is there a way to stop this? Maybe, as @ducdev said, the server needs to respond that the email arrived successfully?
Thanks!

**Comment by ducdev** [comment]
> I'm also seeing this behaviour on my server. I keep receiving the same email over and over.
> Is there a way to stop this? Maybe, as @ducdev said, the server needs to respond that the email arrived successfully?
> Thanks!

Bro, I'm happy with https://www.npmjs.com/package/node-mailin after all.

**Comment by jvlobo** [comment]
Thanks mate, will take a look :)

**Comment by andris9** [comment]
You get multiple emails if you do not properly acknowledge the message so that the sender would get a proper 250 success response. If there's a 4xx or 5xx response or timeout then the sender tries again several times.

**Comment by jvlobo** [comment]
Thanks @andris9 
How can we properly acknowledge the message so that the sender gets a proper 250 success response?

**Comment by andris9** [comment]
You have to always run the callback like shown [here](https://github.com/nodemailer/smtp-server/blob/master/examples/server.js#L104). This triggers the 250 response. If the callback is not called or is called with an error then the message is most probably retried

**Comment by jvlobo** [comment]
Thank you @andris9 👍🏽

**Comment by andrealeo83** [comment]
thanks @andris9
