### ISSUE TITLE
[typescript] SMTPServerAddress.args: Property 'SIZE' does not exist on type 'object'

### ISSUE THREAD

**Issue by dylan-hart** [nodemailer/smtp-server#163]
I'm using `smtp-server` along with its type definitions `@types/smtp-server`. The `SMTPServerAddress` type appears to declare its `args` property as type `object`:

(taken from https://nodemailer.com/extras/smtp-server/#using-size-extension)

```typescript
// Linter problem: Property 'SIZE' does not exist on type 'object'.
let expectedSize = Number(session.envelope.mailFrom.args.SIZE) || 0;
```

Declaring SMTPServerAddress.args as type `any` or `{ [key: string]: string }` would fix the issue for me.

For now, I'm working around the linter:

```typescript
let expectedSize = Number(session.envelope.mailFrom.args["SIZE"]) || 0;
```

**Comment by andris9** [comment]
Types are managed by 3rd party, you need to contact the maintainer directly
