### ISSUE TITLE
SSL ERROR ERR_SSL_SSLV3_ALERT_BAD_CERTIFICATE

### ISSUE THREAD

**Issue by almostkareem** [nodemailer/smtp-server#168]
Hello,
I have been using this package to receive inbound emails, but some mail servers like gitlab or dribbble cannot send messages to my SMTP server, this the error I get : 

<img width="1085" alt="Capture d’écran 2021-09-14 à 5 59 06 p m" src="https://user-images.githubusercontent.com/24992264/133301450-95277df8-5493-48ae-b3ca-209d171ea968.png">

Thanks, any help appreciated

**Comment by andris9** [comment]
Most probably your TLS certificate is not valid (either expired or CA chain is missing) and these clients are validating the certificate.

**Comment by almostkareem** [comment]
I have not set up any TLS Certificate.

**Comment by andris9** [comment]
In this case SMTP-server is using self generated certificates that are always invalid. You need to provide valid certificates in order to accept mail.

**Comment by almostkareem** [comment]
Please can you give me a doc or something something to achieve this?

**Comment by andris9** [comment]
See the docs here https://nodemailer.com/extras/smtp-server/#tls-and-startls-notice

**Comment by almostkareem** [comment]
After setting up a certificate and a private key I now get :  Error: Socket closed unexpectedly
20|mail-api  |     at TLSSocket.onError (/var/apps/mail-api/node_modules/smtp-server/lib/smtp-server.js:473:29)

**Comment by Zonalds** [comment]
@andris9 I do get the same exact error after setting up the certificate and key. The certificate was issued by Let's encrypt for the host


secure: true,
key: fs.readFileSync("/etc/letsencrypt/live/mail-smtp.sendus.io/privkey.pem"),
cert: fs.readFileSync("/etc/letsencrypt/live/mail-smtp.smtp.sendus.io/fullchain.pem"),  //Also tried to use cert.pem with no sucess

```
 Error: Socket closed unexpectedly
20|mail-api | at TLSSocket.onError (/var/apps/mail-api/node_modules/smtp-server/lib/smtp-server.js:473:29)
```

Any chance you could help with this?
