### ISSUE TITLE
Not compliant RFC answer to AUTH command

### ISSUE THREAD

**Issue by matteomattei** [nodemailer/smtp-server#173]
When we perofrm an AUTH command, the answer must be 344 followed by a space as reported in the [RFC](https://datatracker.ietf.org/doc/html/rfc4954#section-4).
#172 PR fixes it.

**Comment by andris9** [comment]
Released as smtp-server@3.10.0

**Comment by andris9** [comment]
Released  zone-mta@3.3.0
