### ISSUE TITLE
Thoughts on setting a maxRecipients length?  e.g. this.session.envelope.rcptTo.length

### ISSUE THREAD

**Issue by titanism** [nodemailer/smtp-server#179]
RCPT TO command can take infinite number of recipients, which is a memory DDoS in server applications

**Comment by andris9** [comment]
SMTPServer is a low level protocol handler, it only runs the most basic checks and all the rejection logic is up to the actual application.

For maximum recipients, see how ZoneMTA handles it with SMTPServer: https://github.com/zone-eu/zone-mta/blob/c918ed970ad80f881549cd8e0d40f060302d79df/lib/smtp-interface.js#L178

Also, all address format validation must be handled by the app (check the same linked method).

I have no plans to change this behavior.
