### ISSUE TITLE
Session envelope contents lost after receiving data from same session

### ISSUE THREAD

**Issue by williamd5** [nodemailer/smtp-server#184]
I set up my `smtp-server` to `console.log` and allow all connect, mail from, rcpt to, auth, data

TLS
```sh
openssl s_client -starttls smtp -crlf -connect localhost:587
```
SMTP
1. **`auth login`**
  I have `callback(null, {user: "test"})`
2. **`helo test`**
3. **`mail from: <test@example.com>`**
  `session.envelope` is
  ```js
  { mailFrom: { address: 'test@example.com', args: false }, rcptTo: [] }
  ```
4. **`rcpt to: <johndoe@example.com>`**
  `session.envelope` is
  ```js
  {
    mailFrom: { address: 'test@domain.com', args: false },
    rcptTo: [ { address: 'johndoe@domain.com', args: false } ]
  }
  ```
5. **`data`**
  ```
  To:  John Doe <johndoe@example.com>
  From: Test <test@example.com>
  Subject: Hello world
  
  asd hello
  world
  
  .
  ```
  `session.envelope` is
```js
{ mailFrom: false, rcptTo: [] }
```

What is the reason for the envelope object to change after receiving data? Should I store its contents before receiving data? What if data is never sent?

**Comment by andris9** [comment]
SMTP client can send multiple emails and the session is reset after each data completion

**Comment by williamd5** [comment]
> SMTP client can send multiple emails and the session is reset after each data completion

what is the best practice to obtain mail from and rcpt to data when the data is submitted?

**Comment by williamd5** [comment]
@andris9 I have still not figured this out.

Are you certain that when receiving `data` the envelope should *already* be cleared? How am I supposed to access the envelope when I receive the data?

Any pointers would be much appreciated.
