### ISSUE TITLE
SMTP Server Capturing and Storing Old Emails Unintentionally

### ISSUE THREAD

**Issue by Harmish-Babariya** [nodemailer/smtp-server#196]
Issue Overview:
I am encountering an unexpected behavior with my SMTP server where it is capturing and storing old emails, even though the server is not configured to retain any email data. The server's primary purpose is to handle incoming emails and process them based on standard SMTP behavior. However, it appears that the server is unintentionally capturing emails from the past.

**Comment by andris9** [comment]
Just like express.js can not provide you "http requests from the past", smtp-server can not provide you with emails from the past. smtp-server is just a protocol handler, nothing else.

**Comment by Harmish-Babariya** [comment]
It capturing past email.
when i start server (node server.js), it is stable. Then i sent one email from gmail and then email is received by server done.
After that it starting capturing old email (also yesterday mail that i sent to my server ) and also capture current email more times

**Comment by andris9** [comment]
Sounds like a bug in your code. Make sure you are not calling the callback function multiple times etc.

**Comment by Harmish-Babariya** [comment]
SMPT server code:
const SMTPServer = require("smtp-server").SMTPServer;
const simpleParser = require("mailparser").simpleParser;

const server = new SMTPServer({
  logger: true,
  onData(stream, session, callback) {
    simpleParser(stream, {}, (err, parsed) => {
      if (err) {
        console.log("Error:", err);
        return callback(err);
      }
      console.log(parsed);
      stream.on("end", callback);
    });
  },
 disabledCommands: ['AUTH']
});

server.listen(25);

**Comment by andris9** [comment]
There is absolutely no way this code retriggers old messages by itself

**Comment by Harmish-Babariya** [comment]
How can I prove that it recapture old email even yesterday email ? 
By just one new current email, it staring capturing old email 😄.

**Comment by andris9** [comment]
I'd suggest turning logging on for smtp-server `logger: true, debug: true`, maybe adding some debug breakpoints or printing info to the console etc., and then going through that information to find clues of what is going on. Currently, there is no way I believe the smtp-server is capturing old emails by itself without actual proof and reasoning of how and why it would do so.

**Comment by Harmish-Babariya** [comment]
I know smtp server just accepting the connection from other host like as in my case Gmail. But from one connection it trigger other connection from Gmail and starting accepting email(old). I can guess that this is Gmail issue. But If it is , then we don't receive duplicate mail in our Gmail.
I don't know what's happening.
