### ISSUE TITLE
TLS with Letsencrypt not working (ConnectionRefusedError)

### ISSUE THREAD

**Issue by terion-name** [nodemailer/smtp-server#198]
After enabling tls smtp connection can't establish (testing with thunderbird) — getting `ConnectionRefusedError`

Tried different configuration options, currently this:

```ts
const smtpConfig = {
        secure: !!sslDomain,
        name: sslDomain || 'localhost',
        tls: {
            rejectUnauthorized: false,
            servername: sslDomain || 'localhost'
        },
        debug: env.NODE_ENV === "development",
        authOptional: false,
        allowInsecureAuth: true,
        key: sslDomain ? fs.readFileSync(`${env.CERT_DIR}${sslDomain}/privkey.pem`, 'utf-8') : undefined,
        cert: sslDomain ? fs.readFileSync(`${env.CERT_DIR}${sslDomain}/cert.pem`, 'utf-8') : undefined,
        ca: sslDomain ? fs.readFileSync(`${env.CERT_DIR}${sslDomain}/fullchain.pem`, 'utf-8') : undefined,
        onAuth(auth, session, callback) {
            log('auth', session)
            callback()
        },
        onData,
        onConnect(session, callback) {
            log('Connected', session)
            callback()
        },
        onSecure(socket, session, callback) {
            log('Secure', session)
            callback()
        }
    }
```

Certs are from letsencrypt, the domain is public but pointing to 127.0.0.1 for testing

Even with `rejectUnauthorized: false` and `allowInsecureAuth: true` — no luck

Without ssl on 587 port everything is working fine

Several days of debug and nothing =(

**Comment by andris9** [comment]
Make sure you have set the port and host correctly, and then use the `openssl` tool to test the connection

```
$ openssl s_client -crlf -servername example.com -connect 127.0.0.1:465
```

If the connection attempt does not show up in SMTP-Server's output log, you are connecting to somewhere else, but not against the SMTP-Server.

**Comment by terion-name** [comment]
> Make sure you have set the port and host correctly, and then use the `openssl` tool to test the connection
> 
> ```
> $ openssl s_client -crlf -servername example.com -connect 127.0.0.1:465
> ```
> 
> If the connection attempt does not show up in SMTP-Server's output log, you are connecting to somewhere else, but not against the SMTP-Server.

```
openssl s_client -crlf -servername localhost.**** -connect 127.0.0.1:465
CONNECTED(00000003)
```

**Comment by terion-name** [comment]
@andris9 my mistake in issue description: not `ConnectionRefusedError` but `NetworkTimeoutError`, copied from old logs

**Comment by terion-name** [comment]
@andris9 well, I've figured out. I've run it in Bun — and it doesn't work there =( With node it's ok..
