### ISSUE TITLE
SNI and multiple hostnames

### ISSUE THREAD

**Issue by AroaR91867HTML** [nodemailer/smtp-server#208]
Hi,

I have a SMTP server with TLS (just to receive emails) but now we want to add multiple domains, I read in the doc about SNI, but I can't see how I can specify an individual certificate (key, cert) for each domain.

Thank you

**Comment by andris9** [comment]
You can use something like this:
```
sniOptions: {
  "smtp.example.com": {
    key: fs.readFileSync("private.key"),
    cert: fs.readFileSync("server.crt")
  }
}
```

**Comment by AroaR91867HTML** [comment]
Thank you!
