### ISSUE TITLE
How to make secure server ?

### ISSUE THREAD

**Issue by websharik** [nodemailer/smtp-server#215]
All test and mail services send packets to 25 port (i was look trafic by ports). So i require server on 25 port with redirect to 465 ? How to do it ? How it must work ?

I was try just that config, but all testers will try connect only to 25 port, then ends with error timeout. (465 is open and work)
```ts
    this.server = new SMTPServer({
      logger: true,
      secure: true,
      //cert from letsencrypt for my mail domain (ex mail.example.com)
      key: fs.readFileSync('privkey.pem', 'utf8'),
      cert: fs.readFileSync('cert.pem', 'utf8'),
      ca: fs.readFileSync('fullchain.pem', 'utf8'),
      onData,
      disabledCommands: ['AUTH']
    })
    this.server.on('error', err => console.log('Error:', err))
    this.server.listen(465, '0.0.0.0')
```

25 port + secure config is too "timeout" (but server shows Error: Socket closed unexpectedly)
just 25 without secure config works fine (but it not secure)
Double server (unsecured 25 + secured 465) works wrong (only 25 using)

25 port without secure, receive mail from gmail, part log:
```
[2024-08-27 13:39:27] DEBUG [#dhqeha4xw4ahufhu] C: STARTTLS
[2024-08-27 13:39:27] DEBUG [#dhqeha4xw4ahufhu] S: 220 Ready to start TLS
[2024-08-27 13:39:27] INFO  [#dhqeha4xw4ahufhu] Connection upgraded to TLS using  TLS_AES_256_GCM_SHA384
[2024-08-27 13:39:27] DEBUG [#dhqeha4xw4ahufhu] C: EHLO mail-ed1-f44.google.com
```
Its force secured by google ? Its safe ? My side secure with letsencrypt more safe ?

**Comment by Carlgo11** [comment]
@websharik you're mixing up the submission and exchange ports.
Server-to-server traffic will only be done over port 25 and you can’t set the secure flag on that port.
When a server connects (like Gmail), it will connect to port 25 and only then will it initiate an encrypted session, using STARTTLS.
If you want to force encryption on port 25, make sure the session is secure when the MAIL FROM command is used.

**Comment by websharik** [comment]
My last used version is: 25 port + secure false + key cert and CA (if not set, TLS will use self-signed localhost) + 530 Encryption required on Mail From if unsecured.

@Carlgo11 Thanks, now I better understand how it works. Can you explain why some testers show "No TLS / SSL support" on my domain (while the same testers on smtp.gmail.com show "TLS/SSL ok")? The connection logs show STARTTLS + 220 Ready to start TLS, and the "session" is marked as secured.

**Comment by Carlgo11** [comment]
@websharik you're welcome. I'm not super familiar with this project, but am somewhat familiar with email standards.

>`secure: true` using only for client-server connections and secure server must be external, right ?

The `secure` flag means that TLS is required from the beginning of the session. Although you can technically use it for client-server communication, it is mostly deprecated nowadays in favor of STARTTLS on port 587.


>My last used version is: 25 port + secure false + key cert and CA (if not set, TLS will use self-signed localhost) + "530 Encryption required" on Mail From if unsecured.

According to the [documentation](https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener), the `ca` option is only used for client certificate authentication, so unless you also use `requestCert: true`, it isn't needed. It's also a client-server-only option, as exchange servers don't send client certificates.

I have no idea why the tests you run report what it does. My only suggestion is to log the socket at onSecure() and maybe that tells you what the issue could be. My [tls configuration](https://github.com/Carlgo11/mailroom/blob/master/inbox/src/config/tls.js) might be helpful for you to compare against.
