### ISSUE TITLE
Returning an Error to onConnect has no effect

### ISSUE THREAD

**Issue by CliffS** [nodemailer/smtp-server#78]
In its simplest form, I have:

    var server = new SMTPServer({
       onConnect: function(session, callback) {
            callback(new Error "Blacklisted");
        }
    });

I get:

    554 Blacklisted
    220 mail.might.be ESMTP

whereas I would have expected it to drop the connection.  If the client ignores the 554, it can carry on and send mail.

What am I missing?

**Comment by andris9** [comment]
Oh, dang, this seems to have been around for a long time without no-one noticing. Fixed and released as v2.0.2

**Comment by CliffS** [comment]
Thank you for that speedy response and fix.
