### ISSUE TITLE
CRAM-MD5 on open channel

### ISSUE THREAD

**Issue by CliffS** [nodemailer/smtp-server#79]
I'm building an SMTP proxy to put in front of Communigate.
 
I have a situation where I have some SMTP users who authenticate on port 587 with CRAM-MD5 but who do not use STARTTLS.  Communigate will happily supply the plain-txt password.

According to the docs:

> Authentication is only allowed in secure mode (either the server is started with `secure: true` option or STARTTLS command is used)

However, it is not unreasonable (server security issues aside) to use CRAM-MD5 without TLS as no clear-text password crosses the Internet.

It would be useful (a) if the `session` object contained a flag to show whether this was an encrypted session and (b) if onAuth() were always called but  where `username` and `password` were null for unencrypted sessions.

would you consider this?

**Comment by CliffS** [comment]
Actually, I had missed the `allowInsecureAuth` option.

With this, it's just a two-line change to the code.  I'll send you a PR.

**Comment by andris9** [comment]
I merged the PR and published the code as v2.0.3. Sorry for the delay.
