### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by djMax** [nodemailer/smtp-server#81]
This GPL/EUPL thing is a bit odd in the context of a node module, IMHO. Can you clarify whether your intent is that someone using this module in an SMTP server they host (either on-premise or on AWS) for themselves (e.g. not selling or distributing that server to someone else) would have to GPL their server code?

**Comment by andris9** [comment]
My intent is that companies would buy the [commercial license of Nodemailer](https://gumroad.com/l/nodemailer) and to make the offer a bit better I throw in, for the same terms, some lesser code of mine as well, like this server module, a mail parsing module etc. IANAL, I guess the best resource on EUPL license usage would be the [official guidelines](https://joinup.ec.europa.eu/sites/default/files/ckeditor_files/files/EUPL%201_1%20Guidelines%20EN%20Joinup.pdf) published by the EU.

**Comment by dex4er** [comment]
This is difficult question but I have to ask anyway... Do you plan to support smtp-server 1.x on MIT license?

I already forked you're project but my intention is to use the branch on MIT license with necessary patches and if you'll make additional maintenance of this branch and I'll switch back to your source code.

**Comment by djMax** [comment]
My reading of EUPL suggests that so long as we don't distribute a derivative work, it's not GPLed. But your intent helps, so thanks. I'll look at the forked version.

**Comment by andris9** [comment]
@dex4er No, I don't plan managing the MIT code anymore. Unless there's something really critical. I've been slowly migrating all my projects from MIT to EUPL and I plan to continue this way. I see the issues this raises but there's always an option to use or fork the existing MIT code.

Personally, my turning point of dropping MIT was when a company that uses Nodemailer and related modules to send huge amounts of email was sold for hundreds of millions of $. Maintaining and developing all this code over the past 6 or 7 years had made me about $500 in donations. It's like the worst paying job ever and I wasn't even able to blame anybody as using MIT I was giving all the rights away for free and no-one was obliged to return anything.

**Comment by andris9** [comment]
Just to point out how smtp-server is even related to Nodemailer - this module was originally part of Nodemailer integration testing stack as I needed a SMTP server for testing email sending from Nodemailer. Turned out to be re-usable for other purposes as well, so I moved it to be a separate project.

**Comment by dex4er** [comment]
@andris9 I totally understand your point of view. I wish you good look with new business. 👍

**Comment by andris9** [comment]
I reverted the license back to MIT (starting from v3.0.0)
