### ISSUE TITLE
Usage...help please

### ISSUE THREAD

**Issue by SPlatten** [nodemailer/smtp-server#82]
I would like to use this module, my code looks like this:

        try{
        	const defs  	 = require("./svr/defs.js");
        	const fs 	 = require("fs");
            const os         = require("os");
         	const SMTPServer = require("smtp-server").SMTPServer;
        	const server 	 = new SMTPServer({
        		onData(stream, session, callback) {
        			stream.pipe(process.stdout); // print message to console
        			stream.on('end', () => {
        // reject every other recipient
        				let response = session.envelope.rcptTo.map((rcpt, i) => {
        					if (i % 2) {
        						return new Error('<' + rcpt.address + '> Not accepted');
        					} else {
        						return '<' + rcpt.address + '> Accepted';
        					}
        				});
        				if ( typeof callback == "function" ) {
        					callback(null, response);
        				}
        			});
        		},onMailFrom(address, session, callback) {
        			console.dir(address);
        			console.dir(session);
        			
        			if ( typeof callback == "function" ) {
        				console.dir(callback);
        				return callback(); // Accept the address
        			}
        		},onRcptTo(address, session, callback) {
        			console.log(address);
        			console.log(session);
        			
        			if ( typeof callback == "function" ) {
        				console.dir(callback);
        				return callback();
        			}
                }
            });
        /*Find the external I/P address for this system*/
        	var objNIs = os.networkInterfaces(), strServerHost;
        	for( var strName in objNIs ) {
        		var aryIFace = objNIs[strName];
        		for( var i=0; i<aryIFace.length; i++ ) {
        			var objNI = aryIFace[i];
        			if ( objNI['internal'] == false && "IPv4".match(objNI['family']) ) { 
        				strServerHost = objNI['address'];
        				break;
        			}
        		}
        		if ( strServerHost !== undefined ) {
        			break;
        		}
        	}
        	if ( strServerHost === undefined ) {
        /*If we couldn't determine the external I/P address use the local address*/
        		strServerHost = "";
        	} 
        /*Start listening for client connections*/
        	server.listen(465, strServerHost);
        } catch( ex ) {
        	console.log(ex);
        }

I've setup a domain name on dynamic DNS which points to my system, previous I have used Haraka and received emails I've sent to my system.  I'm sending emails to the same domain, this time using the above code, but I'm obviously missing something as I don't see any activity.

Is there a working example or please could I have some help on what I need to do ?

Thank you,

**Comment by andris9** [comment]
What do you expect that should happen?

**Comment by SPlatten** [comment]
I was hoping that the email would be received and some of the console messages would be displayed as a result of the callbacks, but I realise I may have missed something, I'm hoping for some guidance to get me started.

**Comment by andris9** [comment]
If you want to receive messages then you should listen on port 25 not 465 which is a submission port

**Comment by andris9** [comment]
You need to disable authentication. See this [example](https://github.com/nodemailer/smtp-server/blob/master/examples/server.js#L29)
