### ISSUE TITLE
Not an issue...

### ISSUE THREAD

**Issue by SPlatten** [nodemailer/smtp-server#84]
Is there any documentation or examples on how to save email attachments?

**Comment by andris9** [comment]
You need something to parse the incoming rfc822 formatted email, eg [mailparser](https://github.com/nodemailer/mailparser/)

**Comment by SPlatten** [comment]
Thank you, I will investigate tonight after work.

**Comment by SPlatten** [comment]
Hi,

I’m trying to learn my way around the mailer and smtp-server as quickly as possible, I’ve attached my source so far.

I am forwarding an existing email from my system to the domain that the smtp server is listening to port 25 on.  This is to emulate what the actual system will do, where emails will be forwarded onto this system, what I want to do is pick up the original email address from the received email, but I’m not sure how to do this, I also want to save the email.

Can you please give me some hints?  Thank you,



Kind Regards,



Simon Platten
simonaplatten@gmail.com

**Comment by andris9** [comment]
If you need to access the addresses from MAIL FROM and RCPT TO commands (eg. the SMTP envelope), then  look into the session object. [Here's an example](https://nodemailer.com/extras/smtp-server/#using-lmtp) for accessing recipient addresses (there might be multiple addresses).

**Comment by SPlatten** [comment]
Thank you, I only need to identify who the email came from and was forwarded by.

Kind regards,
Simon Platten
