### ISSUE TITLE
Limitation?

### ISSUE THREAD

**Issue by Extarys** [nodemailer/smtp-server#86]
Hey!

Is there any limitation compared to Exim4 or Postfix for example?
Or is this works like any other smtp server and can be used in production.

Thanks!

PS.: Any IMAP server in nodejs by any chance?

**Comment by andris9** [comment]
smtp-server is a low level protocol module that only provides smtp interfaces for applications, it does not have any message routing logic or such by itself. For a complete SMTP server application check out Haraka. For an IMAP server in Nodejs check out https://wildduck.email

**Comment by Extarys** [comment]
AWESOME thank you so much!
