### ISSUE TITLE
Can't file issues with mailparser (GH issues disabled)

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/smtp-server#91]
The mailparser repo has GH issues disabled, but I'd like to have this be an option to turn on/off <https://github.com/nodemailer/mailparser/blob/master/lib/simple-parser.js#L60>.

**Comment by niftylettuce** [comment]
Similarly header transformation <https://github.com/nodemailer/mailparser/blob/master/lib/simple-parser.js#L54>

**Comment by andris9** [comment]
I added a new option `keepCidLinks` to the master branch, could you test it out?

```javascript
simpleParser(source, {keepCidLinks: true}, (err, mail)=>{})
```
