### ISSUE TITLE
Unnecessary escape character in mailparser

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/smtp-server#92]
https://github.com/nodemailer/mailparser/blob/2e2cdeaebf08e169bdbf0137cf96d564dda2ae0c/lib/simple-parser.js#L56

Doesn't need the `\` before the `-` in the regex.

**Comment by andris9** [comment]
Yeah, I recently started using a linter rule in my editor that finds these things whenever I edit any files. Haven't touched this one so far but I'll fix it whenever I get to it.
